[project]
name = "learnreidswithme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vardhman Gadade", email = "vardhman@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
learnreidswithme = "learnreidswithme:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
